# Generated by Django 5.0.14 on 2026-05-08 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0002_contactinfo_storysection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='item',
        ),
        migrations.AlterModelOptions(
            name='contactinfo',
            options={'verbose_name': 'Find Us', 'verbose_name_plural': 'Find Us'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Menu Item', 'verbose_name_plural': 'Menu Items'},
        ),
        migrations.AlterModelOptions(
            name='storysection',
            options={'ordering': ['order'], 'verbose_name': 'Our Story Section', 'verbose_name_plural': 'Our Story'},
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='google_maps_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='items/'),
        ),
        migrations.AlterField(
            model_name='storysection',
            name='body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='storysection',
            name='heading',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='storysection',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='storysection',
            name='order',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
