# Generated by Django 5.0.14 on 2026-05-08 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0003_remove_orderitem_order_remove_orderitem_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='google_maps_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
